and_or_limit: 7
default_page: node_search
index:
  cron_limit: 100
  overlap_cjk: true
  minimum_word_size: 3
  tag_weights:
    h1: 25
    h2: 18
    h3: 15
    h4: 14
    h5: 9
    h6: 6
    u: 3
    b: 3
    i: 3
    strong: 3
    em: 3
    a: 10
