# Schema for the configuration files of the User module.

user.settings:
  type: mapping
  label: 'User settings'
  mapping:
    admin_role:
      type: string
      label: 'Administrator role'
    anonymous:
      type: label
      label: 'Name'
    verify_mail:
      type: boolean
      label: 'Require e-mail verification when a visitor creates an account.'
    notify:
      type: mapping
      label: 'Notify user'
      mapping:
        cancel_confirm:
          type: boolean
          label: 'Account cancellation confirmation'
        password_reset:
          type: boolean
          label: 'Notify user when password reset'
        status_activated:
          type: boolean
          label: 'Notify user when account is activated.'
        status_blocked:
          type: boolean
          label: 'Account blocked'
        status_cancelled:
          type: boolean
          label: 'Account canceled'
        register_admin_created:
          type: boolean
          label: 'Welcome (new user created by administrator)'
        register_no_approval_required:
          type: boolean
          label: 'Welcome (no approval required)'
        register_pending_approval:
          type: boolean
          label: 'Welcome (awaiting approval)'
    register:
      type: string
      label: 'Who can register accounts?'
    signatures:
      type: boolean
      label: 'Enable signatures.'
    cancel_method:
      type: string
      label: 'When cancelling a user account'
    password_reset_timeout:
      type: integer
      label: 'Password reset timeout'
    password_strength:
      type: boolean
      label: 'Enable password strength indicator'
    langcode:
      type: string
      label: 'Default language'

user.mail:
 type: mapping
 label: 'E-mail settings'
 mapping:
  cancel_confirm:
    type: mail
    label: 'Account cancellation confirmation'
  password_reset:
    type: mail
    label: 'Password recovery'
  register_admin_created:
    type: mail
    label: 'Account created by administrator'
  register_no_approval_required:
    type: mail
    label: 'Registration confirmation (No approval required)'
  register_pending_approval:
    type: mail
    label: 'Registration confirmation (Pending approval)'
  register_pending_approval_admin:
    type: mail
    label: 'Admin (user awaiting approval)'
  status_activated:
    type: mail
    label: 'Account activation'
  status_blocked:
    type: mail
    label: 'Account blocked'
  status_canceled:
    type: mail
    label: 'Account cancelled'
  langcode:
    type: string
    label: 'Default language'

user.flood:
  type: mapping
  label: 'User flood settings'
  mapping:
    uid_only:
      type: boolean
      label: 'UID only identifier'
    ip_limit:
      type: integer
      label: 'IP limit'
    ip_window:
      type: integer
      label: 'IP window'
    user_limit:
      type: integer
      label: 'User limit'
    user_window:
      type: integer
      label: 'User window'

user.role.*:
  type: mapping
  label: 'User role settings'
  mapping:
    id:
      type: string
      label: 'User role ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'User role label'
    weight:
      type: integer
      label: 'User role weight'
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        - type: string
          label: 'Permission'
    status:
      type: boolean
      label: 'Status'
    langcode:
      type: string
      label: 'Default language'

action.configuration.user_add_role_action:
  type: action_configuration_default
  label: 'Add a role to the selected users configuration'

action.configuration.user_block_user_action:
  type: action_configuration_default
  label: 'Block the selected users configuration'

action.configuration.user_cancel_user_action:
  type: action_configuration_default
  label: 'Cancel the selected user accounts configuration'

action.configuration.user_remove_role_action:
  type: mapping
  label: 'Remove a role from the selected users configuration'
  mapping:
    rid:
      type: sequence
      label: 'Roles'
      sequence:
        - type: sequence
          label: 'Role'

action.configuration.user_unblock_user_action:
  type: action_configuration_default
  label: 'Unblock the selected users configuration'
