# Schema for the user module's migration source plugins.

migrate.source.d6_user:
  type: migrate_source_sql
  label: 'Drupal 6 user'
  mapping:
    constants:
      type: mapping
      label: 'Constants'
      mapping:
        key:
          type: string
          label: 'User data key'
        module:
          type: string
          label: 'Module name'

migrate.source.d6_user_picture_file:
  type: migrate_source_sql
  label: 'Drupal 6 user picure display'
  mapping:
    constants:
      type: mapping
      label: 'Constant'
      mapping:
        is_public:
          type: boolean
          label: 'Public'

migrate.source.d6_user_picture_instance:
  type: migrate_source_sql
  label: 'Drupal 6 user picure display'
  mapping:
    provider:
      type: string
      label: 'Provider'
    constants:
      type: migrate_entity_constant
      label: 'Constants'

migrate.source.d6_profile_field:
  type: migrate_source_sql
  label: 'Drupal 6 profile field'
  mapping:
    constants:
      type: migrate_entity_constant
      label: 'Constants'
