# Schema for the configuration files of the Datetime module.

field.datetime.storage_settings:
  type: mapping
  label: 'Datetime settings'
  mapping:
    datetime_type:
      type: string
      label: 'Date type'

field.datetime.field_settings:
  type: sequence
  label: 'Settings'
  sequence:
    - type: string

field.datetime.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: sequence
      label: 'Default value'
      sequence:
        - type: string
          label: 'Type'
        - type: string
          label: 'Value'

entity_view_display.field.datetime_default:
  type: entity_field_view_display_base
  label: 'Datetime default display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        format_type:
          type: string
          label: 'Date format'

entity_view_display.field.datetime_plain:
  type: entity_field_view_display_base
  label: 'Datetime plain display format settings'

entity_form_display.field.datetime_datelist:
  type: entity_field_form_display_base
  label: 'Datetime select list display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        increment:
          type: integer
          label: 'Time increments'
        date_order:
          type: string
          label: 'Date part order'
        time_type:
          type: string
          label: 'Time type'

entity_form_display.field.datetime_default:
  type: entity_field_form_display_base
  label: 'Datetime default display format settings'
