# Schema for the configuration files of the syslog module.

syslog.settings:
  type: mapping
  label: 'Syslog settings'
  mapping:
    identity:
      type: string
      label: 'Identity'
    facility:
      type: string
      label: 'Facility'
    format:
      type: string
      label: 'Format'
