id: medium
uuid: 17a8d708-e3b1-432d-9d36-542a97346a60
label: 'Default medium date'
status: true
langcode: en
locked: false
locales: {  }
pattern:
  php: 'D, m/d/Y - H:i'
  intl: 'ccc, MM/dd/yyyy - kk:mm'
