first_day: '0'
country:
  default: ''
timezone:
  default: ''
  user:
    configurable: '1'
    default: '0'
    warn: '0'
formats:
  long:
    name: 'Default Long Date'
    pattern:
      php: 'l, F j, Y - H:i'
      intl: 'EEEE, LLLL d, yyyy - kk:mm'
    locked: 0
  medium:
    name: 'Default Medium Date'
    pattern:
      php: 'D, m/d/Y - H:i'
      intl: 'ccc, MM/dd/yyyy - kk:mm'
    locked: 0
  short:
    name: 'Default Short Date'
    pattern:
      php: 'm/d/Y - H:i'
      intl: 'MM/dd/yyyy - kk:mm'
    locked: 0
  html_datetime:
    name: 'HTML Datetime'
    pattern:
      php: 'Y-m-d\TH:i:sO'
      intl: "yyyy-MM-dd'Tkk:mm:ssZZ"
    locked: 1
  html_date:
    name: 'HTML Date'
    pattern:
      php: 'Y-m-d'
      intl: 'yyyy-MM-dd'
    locked: 1
  html_time:
    name: 'HTML Time'
    pattern:
      php: 'H:i:s'
      intl: 'H:mm:ss'
    locked: 1
  html_yearless_date:
    name: 'HTML Yearless date'
    pattern:
      php: 'm-d'
      intl: 'MM-d'
    locked: 1
  html_week:
    name: 'HTML Week'
    pattern:
      php: 'Y-\WW'
      intl: "Y-'WW"
    locked: 1
  html_month:
    name: 'HTML Month'
    pattern:
      php: 'Y-m'
      intl: 'Y-MM'
    locked: 1
  html_year:
    name: 'HTML Year'
    pattern:
      php: 'Y'
      intl: 'Y'
    locked: 1
