cache:
  page:
    enabled: '0'
    omit_vary_cookie: ''
    max_age: '0'
css:
  preprocess: '0'
  gzip: '1'
js:
  preprocess: '0'
  gzip: '1'
response:
  gzip: '0'
stale_file_threshold: '2592000'
theme_link: '1'

