# Schema for the configuration files of the File module.

file.settings:
  type: mapping
  label: 'File settings'
  mapping:
    description:
      type: mapping
      label: 'Description'
      mapping:
        type:
          type: string
          label: 'Type'
        length:
          type: integer
          label: 'Length'
    icon:
      type: mapping
      label: 'Icon'
      mapping:
        directory:
          type: path
          label: 'Directory'

field.file.settings:
  type: mapping
  label: 'File settings'
  mapping:
    display_field:
      type: boolean
      label: 'Enable Display field'
    display_default:
      type: boolean
      label: 'Files displayed by default'
    uri_scheme:
      type: string
      label: 'Upload destination'

field.file.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: string
      label: 'Value'

field.file.instance_settings:
  type: mapping
  label: 'File settings'
  mapping:
    file_directory:
      type: string
      label: 'File directory'
    file_extensions:
      type: string
      label: 'Allowed file extensions'
    max_filesize:
      type: string
      label: 'Maximum upload size'
    description_field:
      type: boolean
      label: 'Enable Description field'

entity_view_display.field.file_default:
  type: entity_field_view_display_base
  label: 'Generic file format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_view_display.field.file_rss_enclosure:
  type: entity_field_view_display_base
  label: 'RSS enclosure format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_view_display.field.file_table:
  type: entity_field_view_display_base
  label: 'Table of files format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_view_display.field.file_url_plain:
  type: entity_field_view_display_base
  label: 'URL to file format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string


entity_form_display.field.file_generic:
  type: entity_field_form_display_base
  label: 'File format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        progress_indicator:
          type: string
          label: 'Progress indicator'
