# Defines PHP related variables.
variables:
  PRIMARY_PHP: "8.5-ubuntu"
  NEXT_PHP_MAJOR: "8.6-ubuntu"
  MINIMUM_PHP: "8.5-ubuntu"

# Used in matrix jobs.
#  parallel:
#    matrix:
#      - _TARGET_PHP: !reference [.php_versions]
.php_versions:
  [8.5-ubuntu]
