base_field: nid
base_table: node
core: 8.x
description: 'A list of nodes marked for display on the front page.'
status: '1'
display:
  default:
    display_options:
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: none
        options: {  }
      empty:
        area_text_custom:
          admin_label: ''
          content: 'No front page content has been created yet.'
          empty: '1'
          field: area_text_custom
          group_type: group
          id: area_text_custom
          label: ''
          relationship: none
          table: views
          tokenize: '0'
          plugin_id: text
        node_listing_empty:
          admin_label: ''
          empty: '1'
          field: node_listing_empty
          group_type: group
          id: node_listing_empty
          label: ''
          relationship: none
          table: node
          plugin_id: node_listing_empty
        title:
          id: title
          table: views
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          empty: '1'
          title: 'Welcome to [site:name]'
          plugin_id: title
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        promote:
          admin_label: ''
          expose:
            description: ''
            identifier: ''
            label: ''
            multiple: '0'
            operator: ''
            operator_id: '0'
            remember: '0'
            remember_roles:
              authenticated: authenticated
            required: '0'
            use_operator: '0'
          exposed: '0'
          field: promote
          group: '1'
          group_info:
            default_group: All
            default_group_multiple: {  }
            description: ''
            group_items: {  }
            identifier: ''
            label: ''
            multiple: '0'
            optional: '1'
            remember: '0'
            widget: select
          group_type: group
          id: promote
          is_grouped: '0'
          operator: '='
          relationship: none
          table: node_field_data
          value: '1'
          plugin_id: boolean
        status:
          expose:
            operator: '0'
          field: status
          group: '1'
          id: status
          table: node_field_data
          value: '1'
          plugin_id: boolean
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      row:
        type: node
        options:
          build_mode: teaser
          comments: '0'
          links: '1'
          view_mode: teaser
      sorts:
        sticky:
          admin_label: ''
          expose:
            label: ''
          exposed: '0'
          field: sticky
          group_type: group
          id: sticky
          order: DESC
          relationship: none
          table: node_field_data
          plugin_id: boolean
        created:
          field: created
          id: created
          order: DESC
          table: node_field_data
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          granularity: second
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          uses_fields: '0'
      title: ''
      header: {  }
      footer: {  }
      relationships: {  }
      fields: {  }
      arguments: {  }
    display_plugin: default
    display_title: Master
    id: default
    position: '0'
  page_1:
    display_options:
      path: node
    display_plugin: page
    display_title: Page
    id: page_1
    position: '1'
  feed_1:
    display_plugin: feed
    id: feed_1
    display_title: Feed
    position: '2'
    display_options:
      sitename_title: '1'
      path: rss.xml
      displays:
        page_1: page_1
        default: '0'
      pager:
        type: some
        options:
          items_per_page: '10'
          offset: '0'
      style:
        type: rss
        options:
          description: ''
          grouping: {  }
          uses_fields: '0'
      row:
        type: node_rss
        options:
          relationship: none
          item_length: default
          links: '0'
label: Frontpage
module: node
id: frontpage
tag: default
langcode: en
