# Schema for the configuration files of the Comment module.

entity_view_display.field.comment_default:
  type: entity_field_view_display_base
  label: 'Comment display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        pager_id:
          type: integer
          label: 'Pager ID'

entity_form_display.field.comment_default:
  type: entity_field_form_display_base
  label: 'Comment display format settings'

action.configuration.comment_publish_action:
  type: action_configuration_default
  label: 'Publish comment configuration'

action.configuration.comment_save_action:
  type: action_configuration_default
  label: 'Save comment configuration'

action.configuration.comment_unpublish_by_keyword_action:
  type: mapping
  label: 'Unpublish comment containing keyword(s) configuration'
  mapping:
    keyword:
      type: sequence
      label: 'Keywords'
      sequence:
        - type: string
          label: 'Keyword'

action.configuration.comment_unpublish_action:
  type: action_configuration_default
  label: 'Unpublish comment configuration'

comment.type.*:
  type: config_entity
  label: 'Comment type settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    target_entity_type_id:
      type: string
      label: 'Target Entity Type ID'
    description:
      type: text
      label: 'Description'

field.comment.storage_settings:
  type: sequence
  label: 'Settings'
  sequence:
    - type: string
      label: 'Setting'

field.comment.value:
  type: sequence
  label: 'Settings'
  sequence:
    - type: mapping
      label: 'Settings'
      mapping:
        status:
          type: integer
          label: 'Status'
        cid:
          type: integer
          label: 'Status'
        last_comment_timestamp:
          type: integer
          label: 'Last comment timestamp'
        last_comment_name:
          type: integer
          label: 'Name'
        last_comment_uid:
          type: integer
          label: 'UID'
        comment_count:
          type: integer
          label: 'Count'

field.comment.field_settings:
  type: mapping
  label: 'Comment settings'
  mapping:
    default_mode:
      type: integer
      label: 'Threading'
    per_page:
      type: integer
      label: 'Comments per page'
    anonymous:
      type: integer
      label: 'Mode'
    form_location:
      type: boolean
      label: ' Allow comment title'
    preview:
      type: integer
      label: 'Preview comment'
