id: d7_dblog_settings
label: Database logging configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - dblog_row_limit
  source_module: dblog
process:
  row_limit: dblog_row_limit
destination:
  plugin: config
  config_name: dblog.settings
