id: bartik.search
uuid: 51f70058-a370-4410-9000-a65488d00e6c
weight: '-1'
status: '1'
langcode: en
region: sidebar_first
plugin: search_form_block
settings:
  label: Search
  module: search
  label_display: visible
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
