id: bartik.help
plugin: system_help_block
status: '1'
settings:
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
label: ''
module: system
region: help
weight: '0'
langcode: en
