id: bartik.tools
weight: '0'
status: '1'
langcode: en
region: sidebar_first
plugin: 'system_menu_block:tools'
settings:
  label: Tools
  module: system
  label_display: visible
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
