id: seven.login
plugin: user_login_block
status: '1'
settings:
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
label: 'User login'
module: user
region: content
weight: '10'
langcode: en
