id: seven.content
plugin: system_main_block
status: '1'
settings:
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
label: ''
module: system
region: content
weight: '0'
langcode: en
label_display: visible
