id: seven_help
theme: seven
uuid: 367d09b7-9638-4faf-bf07-7fe31b2226a0
weight: '0'
status: '1'
langcode: en
region: help
plugin: system_help_block
settings:
  label: 'System Help'
  module: system
  label_display: '0'
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
