id: bartik_content
theme: bartik
weight: 0
status: true
langcode: en
region: content
plugin: system_main_block
settings:
  label: 'Main page content'
  provider: system
  label_display: '0'
visibility:
  path:
    visibility: 0
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
dependencies:
  module:
    - system
  theme:
    - bartik
