id: bartik.powered
uuid: 37cff101-27dc-478d-9d00-b58b9d884039
weight: '10'
status: '1'
langcode: en
region: footer
plugin: system_powered_by_block
settings:
  label: 'Powered by Drupal'
  module: system
  label_display: '0'
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
