id: bartik.login
whois_new_count: '5'
status: '1'
settings:
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
label: 'User login'
module: user
region: sidebar_first
weight: '0'
plugin: user_login_block
langcode: en
