id: seven.login
uuid: 10a9888b-2247-408d-9702-2c0cc9cacba2
weight: '10'
status: '1'
langcode: en
region: content
plugin: user_login_block
settings:
  label: 'User login'
  module: user
  label_display: visible
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path

