format: full_html
editor: ckeditor
settings:
  toolbar:
    rows:
      -
        -
          name: Formatting
          items:
            - Bold
            - Italic
            - Strike
            - Superscript
            - Subscript
            - -
            - RemoveFormat
        -
          name: Linking
          items:
            - DrupalLink
            - DrupalUnlink
        -
          name: Lists
          items:
            - BulletedList
            - NumberedList
        -
          name: Media
          items:
            - Blockquote
            - DrupalImage
            - Table
            - HorizontalRule
        -
          name: 'Block Formatting'
          items:
            - Format
        -
          name: Tools
          items:
            - ShowBlocks
            - Source
  plugins:
    stylescombo:
      styles: ''
image_upload:
  status: true
  scheme: public
  directory: inline-images
  max_size: ''
  max_dimensions:
    width: 0
    height: 0
status: true
langcode: en
