id: node.article.field_tags
entity_type: node
bundle: article
field_name: field_tags
label: Tags
description: 'Enter a comma-separated list of words to describe your content.'
required: false
default_value: {  }
default_value_function: ''
settings: {  }
status: true
langcode: und
