id: node.article.field_image
entity_type: node
bundle: article
field_name: field_image
label: Image
description: ''
required: false
default_value: {  }
default_value_function: ''
settings:
  file_directory: field/image
  file_extensions: 'png gif jpg jpeg'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: true
  title_field: false
  alt_field_required: false
  title_field_required: false
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
status: true
langcode: und
field_type: image
dependencies:
  entity:
    - field.field.node.field_image
    - node.type.article
