format: basic_html
name: 'Basic HTML'
status: '1'
weight: '0'
roles:
  - authenticated
cache: '1'
filters:
  filter_html:
    module: filter
    status: '1'
    weight: '-10'
    settings:
      allowed_html: '<a> <em> <strong> <cite> <blockquote> <code> <ul> <ol> <li> <dl> <dt> <dd> <h4> <h5> <h6> <p> <span> <img>'
      filter_html_help: '0'
      filter_html_nofollow: '0'
  filter_html_image_secure:
    module: filter
    status: '1'
    weight: '9'
    settings: {  }
  filter_htmlcorrector:
    module: filter
    status: '1'
    weight: '10'
    settings: {  }
langcode: en
