format: filtered_html
name: 'Filtered HTML'
status: '1'
weight: '0'
roles:
  - anonymous
  - authenticated
cache: '1'
filters:
  filter_url:
    module: filter
    status: '1'
  filter_html:
    module: filter
    status: '1'
  filter_autop:
    module: filter
    status: '1'
  filter_htmlcorrector:
    module: filter
    status: '1'
langcode: en
