format: full_html
name: 'Full HTML'
status: '1'
weight: '1'
roles:
  - administrator
cache: '1'
filters:
  filter_url:
    module: filter
    status: '1'
  filter_autop:
    module: filter
    status: '1'
  filter_htmlcorrector:
    module: filter
    status: '1'
langcode: en
