id: stark_login
theme: stark
weight: '0'
status: '1'
langcode: en
region: sidebar_first
plugin: user_login_block
settings:
  label: 'User login'
  module: user
  label_display: visible
  cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types: {  }
  visibility__active_tab: edit-visibility-path
