config.sync:
  path: '/admin/config/development/configuration'
  defaults:
    _form: '\Drupal\config\Form\ConfigSync'
    _title: 'Synchronize'
  requirements:
    _permission: 'synchronize configuration'

config.diff:
  path: '/admin/config/development/configuration/sync/diff/{config_file}'
  defaults:
    _content: '\Drupal\config\Controller\ConfigController::diff'
  requirements:
    _permission: 'synchronize configuration'

config.export_download:
  path: '/admin/config/development/configuration/full/export-download'
  defaults:
    _controller: '\Drupal\config\Controller\ConfigController::downloadExport'
  requirements:
    _permission: 'export configuration'

config.export_full:
  path: '/admin/config/development/configuration/full/export'
  defaults:
    _form: '\Drupal\config\Form\ConfigExportForm'
    _title: 'Export'
  requirements:
    _permission: 'export configuration'

config.import_full:
  path: '/admin/config/development/configuration/full/import'
  defaults:
    _form: '\Drupal\config\Form\ConfigImportForm'
    _title: 'Import'
  requirements:
    _permission: 'import configuration'

config.import_single:
  path: '/admin/config/development/configuration/single/import'
  defaults:
    _title: 'Single import'
    _form: '\Drupal\config\Form\ConfigSingleImportForm'
  requirements:
    _permission: 'import configuration'

config.export_single:
  path: '/admin/config/development/configuration/single/export/{config_type}/{config_name}'
  defaults:
    _title: 'Single export'
    _form: '\Drupal\config\Form\ConfigSingleExportForm'
    config_type: NULL
    config_name: NULL
  requirements:
    _permission: 'export configuration'
