# Schema for the configuration files of the Tour module.

tour.tour.*:
  type: mapping
  label: 'Tour settings'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    module:
      type: string
      label: 'Providing module'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Enabled'
    langcode:
      type: string
      label: 'Default language'
    paths:
      type: sequence
      label: 'Path settings'
      sequence:
        - type: path
          label: 'Path'
    tips:
      type: sequence
      label: 'Tips'
      sequence:
        - type: tour.tip.[plugin]
          label: 'Tour tip'

tour.tip:
  type: mapping
  label: 'Tour tip'
  mapping:
    id:
      type: string
      label: 'ID'
    plugin:
      type: string
      label: 'Plugin'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    location:
      type: string
      label: 'Location'
    attributes:
      type: sequence
      label: 'Attributes'
      sequence:
        - type: string
          label: 'Attribute'

tour.tip.text:
  type: tour.tip
  label: 'Textual tour tip'
  mapping:
    body:
      type: text
      label: 'Body'


