# Schema for entity fields, specifying generic component data type information.

# Schema for the base of the view mode display format settings.
entity_field_view_display_base:
  type: mapping
  mapping:
    type:
      type: string
      label: 'Format type machine name'
    weight:
      type: integer
      label: 'Weight'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: entity_view_display.third_party.[%key]
    label:
      type: string
      label: 'Label setting machine name'
    settings:
      type: sequence
      label: 'Settings'

# Schema for the base of the form mode display format settings.
entity_field_form_display_base:
  type: mapping
  mapping:
    type:
      type: string
      label: 'Format type machine name'
    weight:
      type: integer
      label: 'Weight'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: entity_form_display.third_party.[%key]
    settings:
      type: sequence
      label: 'Settings'
