# Schema for Configuration files of the entity module.

core.entity_view_mode.*.*:
  type: mapping
  label: 'Entity view mode settings'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'The human-readable name of the view mode'
    targetEntityType:
      type: string
      label: 'Target entity type'
    status:
      type: boolean
      label: 'Enabled'
    cache:
      type: boolean
      label: 'Cached'
    langcode:
      type: string
      label: 'Default language'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'

core.entity_form_mode.*.*:
  type: config_entity
  label: 'Entity form mode settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    targetEntityType:
      type: string
      label: 'Target entity type'
    cache:
      type: boolean
      label: 'Cache'

# Overview configuration information for view mode or form mode displays.
core.entity_view_display.*.*.*:
  type: config_entity
  label: 'Entity display'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    targetEntityType:
      type: string
      label: 'Target entity type'
    bundle:
      type: string
      label: 'Bundle'
    mode:
      type: string
      label: 'View or form mode machine name'
    content:
      type: sequence
      label: 'Field display formatters'
      sequence:
        - type: entity_view_display.field.[type]
    hidden:
      type: sequence
      label: 'Field display setting'
      sequence:
        - type: boolean
          label: 'Value'

# Overview configuration information for form mode displays.
core.entity_form_display.*.*.*:
  type: config_entity
  label: 'Entity form display'
  mapping:
    id:
      type: string
      label: 'ID'
    targetEntityType:
      type: string
      label: 'Target entity type'
    bundle:
      type: string
      label: 'Bundle'
    mode:
      type: string
      label: 'View or form mode machine name'
    status:
      type: boolean
      label: 'Enabled'
    content:
      type: sequence
      label: 'Field display formatters'
      sequence:
        - type: entity_form_display.field.[type]
    hidden:
      type: sequence
      label: 'Hidden'
      sequence:
        - type: boolean
          label: 'Component'
    dependencies:
      type: config_dependencies
      label: 'Dependencies'

# Default schema for entity display field with undefined type.
entity_view_display.field.*:
  type: entity_field_view_display_base
  label: 'Entity display default'

# Default schema for entity form display field with undefined type.
entity_form_display.field.*:
  type: entity_field_form_display_base
  label: 'Entity form display default'

entity_form_display.field.string:
  type: entity_field_form_display_base
  label: 'Text field display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        size:
          type: integer
          label: 'Size of textfield'
        placeholder:
          type: label
          label: 'Placeholder'

entity_form_display.field.datetime_timestamp:
  type: entity_field_form_display_base
  label: 'Datetime timestamp display format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_form_display.field.boolean_checkbox:
  type: entity_field_form_display_base
  label: 'Boolean checkbox display format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_form_display.field.hidden:
  type: entity_field_form_display_base
  label: '- Hidden - format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string

entity_form_display.field.number:
  type: entity_field_form_display_base
  label: 'Number default display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        placeholder:
          type: label
          label: 'Placeholder'

entity_form_display.field.checkbox:
  type: entity_field_form_display_base
  label: 'Single on/off checkbox format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        display_label:
          type: boolean
          label: 'Use field label instead of the "On value" as label'

entity_view_display.field.number_decimal:
  type: entity_field_view_display_base
  label: 'Number decimal display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        thousand_separator:
          type: string
          label: 'Thousand marker'
        decimal_separator:
          type: string
          label: 'Decimal marker'
        scale:
          type: integer
          label: 'Scale'
        prefix_suffix:
          type: boolean
          label: 'Display prefix and suffix.'

entity_view_display.field.number_integer:
  type: entity_field_view_display_base
  label: 'Number interger display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        thousand_separator:
          type: string
          label: 'Thousand marker'
        prefix_suffix:
          type: boolean
          label: 'Display prefix and suffix.'

entity_view_display.field.number_unformatted:
  type: entity_field_view_display_base
  label: 'Number unformatted display format settings'
  mapping:
    settings:
      type: sequence
      label: 'Settings'
      sequence:
        - type: string
