# Schema for the views plugins of the REST module.

views.display.rest_export:
  type: views_display_path
  label: 'REST display options'

views.row.data_field:
  type: views_row
  label: 'Field row'
  mapping:
    field_options:
      type: sequence
      label: 'Options'
      sequence:
        - type: mapping
          label: 'Row'
          mapping:
            alias:
              type: string
              label: 'Alias for ID'
            raw_output:
              type: boolean
              label: 'Raw output for ID'

views.style.serializer:
  type: views_style
  label: 'Serialized output format'
  mapping:
    formats:
      type: sequence
      label: 'Formats'
      sequence:
        - type: string
          label: 'Format'
