# Basic data types for image.

image_size:
  type: mapping
  mapping:
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'

field_default_image:
  type: mapping
  mapping:
    fid:
      type: integer
      label: 'Image'
    alt:
      type: label
      label: 'Alternate text'
    title:
      type: label
      label: 'Title'
    width:
      type: integer
      label: 'Width'
    height:
      type: integer
      label: 'Height'
