# Schema for configuration files of the Image module.

image.style.*:
  type: config_entity
  label: 'Image style'
  mapping:
    name:
      type: string
    label:
      type: label
      label: 'Label'
    effects:
      type: sequence
      sequence:
        - type: mapping
          mapping:
            id:
              type: string
            data:
              type: image.effect.[%parent.id]
            weight:
              type: integer
            uuid:
              type: string
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: image_style.third_party.[%key]

image.effect.image_crop:
  type: image_size
  label: 'Image crop'
  mapping:
    anchor:
      label: 'Anchor'
      type: string

image.effect.image_resize:
  type: image_size
  label: 'Image resize'

image.effect.image_rotate:
  type: mapping
  label: 'Image rotate'
  mapping:
    degrees:
      type: integer
      label: 'Rotation angle'
    bgcolor:
      label: 'Background color'
      type: color_hex
    random:
      type: boolean
      label: 'Randomize'

image.effect.image_scale:
  type: image_size
  label: 'Image scale'
  mapping:
    upscale:
      type: boolean
      label: 'Upscale'

# The image desaturate effect has no settings.
image.effect.image_desaturate:
  type: sequence

image.effect.image_scale_and_crop:
  type: image_size
  label: 'Image scale and crop'

image.settings:
  type: mapping
  mapping:
    preview_image:
      type: string
      label: 'Preview image'
    allow_insecure_derivatives:
      type: boolean
      label: 'Allow insecure image derivatives'
    suppress_itok_output:
      type: boolean
      label: 'Suppress the itok query string for image derivatives'

field.image.storage_settings:
  type: field.file.storage_settings
  label: 'Image settings'
  mapping:
    default_image:
      type: field_default_image
      label: 'Default value'

field.image.field_settings:
  type: base_file_field_field_settings
  label: 'Image settings'
  mapping:
    max_resolution:
      type: string
      label: 'Maximum image resolution'
    min_resolution:
      type: string
      label: 'Minimum image resolution'
    alt_field:
      type: boolean
      label: 'Enable Alt field'
    alt_field_required:
      type: boolean
      label: 'Alt field required'
    title_field:
      type: boolean
      label: 'Enable Title field'
    title_field_required:
      type: boolean
      label: 'Title field required'
    default_image:
      type: field_default_image
      label: 'Default value'

field.image.value:
  type: sequence
  label: 'Default value'
  sequence:
    - type: mapping
      label: 'Default image'
      mapping:
        fid:
          type: integer
          label: 'File ID'
        alt:
          type: string
          label: 'Alternative text'
        title:
          type: string
          label: 'Title text'
        width:
          type: integer
          label: 'Width'
        height:
          type: integer
          label: 'Height'

entity_view_display.field.image:
  type: entity_field_view_display_base
  label: 'Image field display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        image_link:
          type: string
          label: 'Link image to'
        image_style:
          type: string
          label: 'Image style'

entity_form_display.field.image_image:
  type: entity_field_form_display_base
  label: 'Image field display format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        progress_indicator:
          type: string
          label: 'Progress indicator'
        preview_image_style:
          type: string
          label: 'Preview image style'
