disabled: true
api_version: '3.0'
name: taxonomy_term
description: 'A view to emulate Drupal core''s handling of taxonomy/term.'
tag: default
base_table: node
human_name: 'Taxonomy term'
core: '7'
display:
    default:
        id: default
        display_title: Master
        display_plugin: default
        position: '1'
        display_options:
            query:
                type: views_query
                options:
                    query_comment: false
            access:
                type: none
            cache:
                type: none
            exposed_form:
                type: basic
            pager:
                type: full
            style_plugin: default
            row_plugin: node
            sorts:
                sticky:
                    id: sticky
                    table: node
                    field: sticky
                    order: DESC
                created:
                    id: created
                    table: node
                    field: created
                    order: DESC
            arguments:
                term_node_tid_depth:
                    id: term_node_tid_depth
                    table: node
                    field: term_node_tid_depth
                    default_action: 'not found'
                    exception:
                        title_enable: 1
                    title_enable: 1
                    title: '%1'
                    default_argument_type: fixed
                    summary:
                        format: default_summary
                    specify_validation: 1
                    validate:
                        type: taxonomy_term
                    depth: '0'
                    break_phrase: 1
                term_node_tid_depth_modifier:
                    id: term_node_tid_depth_modifier
                    table: node
                    field: term_node_tid_depth_modifier
                    exception:
                        title_enable: 1
                    default_argument_type: fixed
                    summary:
                        format: default_summary
                    specify_validation: 1
            filters:
                status_extra:
                    id: status_extra
                    table: node
                    field: status_extra
                    group: 0
                    expose:
                        operator: false
    page:
        id: page
        display_title: Page
        display_plugin: page
        position: '2'
        display_options:
            query:
                type: views_query
                options: {  }
            path: taxonomy/term/%
    feed:
        id: feed
        display_title: Feed
        display_plugin: feed
        position: '3'
        display_options:
            query:
                type: views_query
                options: {  }
            pager:
                type: full
                options:
                    items_per_page: 15
            style_plugin: rss
            row_plugin: node_rss
            path: taxonomy/term/%/%/feed
            displays:
                page: page
                default: 0
