id: d7_language_negotiation_settings
label: Language negotiation settings
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - locale_language_negotiation_session_param
    - locale_language_negotiation_url_part
  source_module: locale
process:
  session/parameter:
    plugin: default_value
    source: locale_language_negotiation_session_param
    default_value: 'language'
  selected_langcode:
    plugin: default_value
    default_value: 'site_default'
  url/source:
    plugin: static_map
    source: locale_language_negotiation_url_part
    default_value: path_prefix
    map:
      # LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX = 0
      # LOCALE_LANGUAGE_NEGOTIATION_URL_DOMAIN = 1
      0: path_prefix
      1: domain
destination:
  plugin: config
  config_name: language.negotiation
migration_dependencies:
  required:
    - language
