base_field: cid
base_table: comment
core: '8'
description: 'A block and a page with recent comments.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_tags: {  }
      title: 'Recent comments'
      use_more: '1'
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: some
        options:
          items_per_page: '5'
          offset: '0'
      relationships:
        nid:
          id: nid
          table: comment
          field: nid
          plugin_id: standard
          relationship: none
          group_type: group
          admin_label: Content
          required: '0'
          provider: views
      fields:
        subject:
          id: subject
          table: comment
          field: subject
          label: ''
          link_to_comment: '1'
          plugin_id: comment
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_node: '0'
          provider: comment
        timestamp:
          id: timestamp
          table: comment
          field: changed
          label: ''
          date_format: 'time ago'
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          custom_date_format: ''
          timezone: ''
          provider: views
      sorts:
        changed:
          id: changed
          table: comment
          field: changed
          order: DESC
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exposed: '0'
          expose:
            label: ''
          granularity: second
          provider: views
      filters:
        status_extra:
          id: status_extra
          table: node_field_data
          field: status_extra
          relationship: nid
          group: '0'
          plugin_id: node_status
          provider: node
      style:
        type: html_list
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          uses_fields: '0'
          type: ul
          class: ''
          wrapper_class: item-list
      row:
        type: fields
        options:
          inline: {  }
          separator: ''
          hide_empty: '0'
          default_field_elements: '1'
      header: {  }
      footer: {  }
      empty: {  }
      arguments: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      defaults:
        style_plugin: '0'
        style_options: '0'
        row_plugin: '0'
        row_options: '0'
        fields: '0'
      fields:
        title:
          id: title
          table: node_field_data
          field: title
          relationship: nid
          label: 'Reply to'
          link_to_node: '1'
          plugin_id: node
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          provider: node
        timestamp:
          id: timestamp
          table: comment
          field: changed
          label: ''
          date_format: 'time ago'
          plugin_id: date
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          custom_date_format: ''
          timezone: ''
          provider: views
        subject:
          id: subject
          table: comment
          field: subject
          label: ''
          link_to_comment: '1'
          plugin_id: comment
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_node: '0'
          provider: comment
        comment:
          id: comment
          table: comment__comment_body
          field: comment_body
          label: ''
          plugin_id: field
          relationship: none
          group_type: group
          admin_label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          click_sort_column: value
          type: text_default
          settings: {  }
          group_column: value
          group_columns: {  }
          group_rows: '1'
          delta_limit: all
          delta_offset: '0'
          delta_reversed: '0'
          delta_first_last: '0'
          multi_type: separator
          separator: ', '
          field_api_classes: '0'
          provider: field
      path: comments/recent
      style:
        type: html_list
      row:
        type: fields
        options:
          inline:
            title: title
            timestamp: timestamp
            separator: '&nbsp;'
  block_1:
    id: block_1
    display_title: Block
    display_plugin: block
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
label: 'Recent comments'
module: comment
id: comments_recent
tag: default
langcode: en
