base_field: nid
base_table: node
core: '8'
description: 'A list of months that link to content for that month.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
      title: 'Monthly archive'
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: mini
      sorts:
        created:
          id: created
          table: node
          field: created
          order: DESC
          plugin_id: date
      arguments:
        created_year_month:
          id: created_year_month
          table: node
          field: created_year_month
          default_action: summary
          exception:
            title_enable: '1'
          title_enable: '1'
          title: '%1'
          default_argument_type: fixed
          summary:
            sort_order: desc
            format: default_summary
          summary_options:
            override: '1'
            items_per_page: '30'
          specify_validation: '1'
          plugin_id: node_created_year_month
      filters:
        status:
          id: status
          table: node
          field: status
          value: '1'
          group: '0'
          expose:
            operator: '0'
          plugin_id: boolean
      style:
        type: default
      row:
        type: node
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: archive
  block_1:
    id: block_1
    display_title: Block
    display_plugin: block
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
      defaults:
        arguments: '0'
      arguments:
        created_year_month:
          id: created_year_month
          table: node
          field: created_year_month
          default_action: summary
          exception:
            title_enable: '1'
          title_enable: '1'
          title: '%1'
          default_argument_type: fixed
          summary:
            format: default_summary
          summary_options:
            items_per_page: '30'
          specify_validation: '1'
          plugin_id: date_year_month
human_name: Archive
module: node
id: archive
tag: default
langcode: en
