disabled: true
api_version: '3.0'
module: node
name: frontpage
description: 'Emulates the default Drupal front page; you may set the default home page path to this view to make it your front page.'
tag: default
base_table: node
human_name: 'Front page'
core: '8'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: false
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: full
      style:
        type: default
      row:
        type: node
        options:
          links: 1
      sorts:
        sticky:
          id: sticky
          table: node
          field: sticky
          order: DESC
        created:
          id: created
          table: node
          field: created
          order: DESC
      filters:
        promote:
          id: promote
          table: node
          field: promote
          value: '1'
          group: 0
          expose:
            operator: false
        status:
          id: status
          table: node
          field: status
          value: '1'
          group: 0
          expose:
            operator: false
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: frontpage
  feed_1:
    id: feed_1
    display_title: Feed
    display_plugin: feed
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
      defaults:
        title: false
      title: 'Front page feed'
      pager:
        type: some
      style:
        type: rss
      row:
        type: node_rss
      path: rss.xml
      displays:
        default: default
        page: page
      sitename_title: '1'
