base_field: nid
base_table: node
core: '8'
description: 'Shows all new activity on the system.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
      title: 'Recent posts'
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: mini
        options:
          items_per_page: '25'
      relationships:
        uid:
          id: uid
          table: node
          field: uid
          plugin_id: standard
      fields:
        type:
          id: type
          table: node
          field: type
          plugin_id: node_type
        title:
          id: title
          table: node
          field: title
          plugin_id: node
        name:
          id: name
          table: users
          field: name
          relationship: uid
          label: Author
          plugin_id: user_name
        comment_count:
          id: comment_count
          table: node_comment_statistics
          field: comment_count
          label: Replies
          plugin_id: numeric
        last_comment_timestamp:
          id: last_comment_timestamp
          table: node_comment_statistics
          field: last_comment_timestamp
          label: 'Last Post'
          plugin_id: comment_last_timestamp
        timestamp:
          id: timestamp
          table: history
          field: timestamp
          label: ''
          link_to_node: '0'
          comments: '1'
          plugin_id: node_history_user_timestamp
        new_comments:
          id: new_comments
          table: node
          field: new_comments
          label: ''
          hide_empty: '1'
          suffix: ' new'
          link_to_comment: '1'
          plugin_id: node_new_comments
      sorts:
        last_comment_timestamp:
          id: last_comment_timestamp
          table: node_comment_statistics
          field: last_comment_timestamp
          plugin_id: date
      arguments:
        uid_touch:
          id: uid_touch
          table: node
          field: uid_touch
          exception:
            title_enable: '1'
          title_enable: '1'
          title: 'Recent posts for %1'
          default_argument_type: fixed
          summary:
            format: default_summary
          specify_validation: '1'
          plugin_id: argument_comment_user_uid
      filters:
        status:
          id: status
          table: node
          field: status
          value: '1'
          group: '0'
          expose:
            operator: '0'
          plugin_id: boolean
      style:
        type: table
        options:
          columns:
            type: type
            title: title
            name: name
            comment_count: comment_count
            last_comment_timestamp: last_comment_timestamp
            timestamp: title
            new_comments: comment_count
          default: last_comment_timestamp
          info:
            type:
              sortable: '1'
              separator: ''
            title:
              sortable: '1'
              separator: '&nbsp;'
            name:
              sortable: '1'
              separator: ''
            comment_count:
              sortable: '1'
              separator: '<br />'
            last_comment_timestamp:
              sortable: '1'
              separator: '&nbsp;'
            timestamp:
              separator: ''
            new_comments:
              separator: ''
          override: '1'
          order: desc
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: tracker
      menu:
        type: normal
        title: 'Recent posts'
label: Tracker
module: node
id: tracker
tag: default
langcode: en
