base_field: cid
base_table: comment
core: '8'
description: 'A block and a page with recent comments.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
      title: 'Recent comments'
      use_more: '1'
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: some
        options:
          items_per_page: '5'
      relationships:
        nid:
          id: nid
          table: comment
          field: nid
          plugin_id: standard
      fields:
        subject:
          id: subject
          table: comment
          field: subject
          label: ''
          link_to_comment: '1'
          plugin_id: comment
        timestamp:
          id: timestamp
          table: comment
          field: changed
          label: ''
          date_format: 'time ago'
          plugin_id: date
      sorts:
        timestamp:
          id: timestamp
          table: comment
          field: changed
          order: DESC
          plugin_id: date
      filters:
        status_extra:
          id: status_extra
          table: node
          field: status_extra
          relationship: nid
          group: '0'
          plugin_id: node_status
      style:
        type: html_list
      row:
        type: fields
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      defaults:
        style_plugin: '0'
        style_options: '0'
        row_plugin: '0'
        row_options: '0'
        fields: '0'
      fields:
        title:
          id: title
          table: node
          field: title
          relationship: nid
          label: 'Reply to'
          link_to_node: '1'
          plugin_id: node
        timestamp:
          id: timestamp
          table: comment
          field: changed
          label: ''
          date_format: 'time ago'
          plugin_id: date
        subject:
          id: subject
          table: comment
          field: subject
          label: ''
          link_to_comment: '1'
          plugin_id: comment
        comment:
          id: comment
          table: field_data_comment_body
          field: comment_body
          label: ''
          plugin_id: field
      path: comments/recent
      style:
        type: html_list
      row:
        type: fields
        options:
          inline:
            title: title
            timestamp: timestamp
            separator: '&nbsp;'
  block_1:
    id: block_1
    display_title: Block
    display_plugin: block
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
human_name: 'Recent comments'
module: comment
id: comments_recent
tag: default
langcode: en
