# Schema for the views plugins of the Language module.

views.argument.language:
  type: views_argument
  label: 'Language'

views.field.language:
  type: views_field
  label: 'Language'

views.filter.language:
  type: views.filter.in_operator
  label: 'Language'

views.filter_value.language:
  type: string
  label: 'Language'
