# Schema for the views style plugins.

views.style.*:
  type: views_style
  label: 'Default style'

views.style.default:
  type: views_style
  label: 'Unformatted list'

views.style.html_list:
  type: views_style
  label: 'HTML List'
  mapping:
    type:
      type:  string
      label: 'List type'
    wrapper_class:
      type: string
      label: 'Wrapper class'
    class:
      type: string
      label: 'List class'

views.style.grid:
  type: views_style
  label: 'Grid'
  mapping:
    columns:
      type:  integer
      label: 'Number of columns'
    alignment:
      type: string
      label: 'Alignment'
    fill_single_line:
      type: boolean
      label: 'Fill up single line'
    summary:
      type: string
      label: 'Table summary'

views.style.table:
  type: views_style
  label: 'Table'
  mapping:
    columns:
      type: sequence
      label: 'Columns'
      sequence:
        - type: string
          label: 'Columns name'
    default:
      type: string
      label: 'Default sort'
    info:
      type: sequence
      label: 'Columns info'
      sequence:
        - type: mapping
          label:  'Column info'
          mapping:
            sortable:
              type: boolean
              label: 'Sortable'
            default_sort_order:
              type: string
              label: 'Default order'
            align:
              type: string
              label: 'Align'
            separator:
              type: string
              label: 'Separator'
            empty_column:
              type: boolean
              label: 'Hide empty columns'
            responsive:
              type: string
              label: 'Responsive'
    override:
      type: boolean
      label: 'Override normal sorting if click sorting is used'
    sticky:
      type: boolean
      label: 'Enable Drupal style "sticky" table headers (Javascript)'
    summary:
      type: label
      label: 'Table summary'
    order:
      type: string
      label: 'Default order'
    empty_table:
      type: boolean
      label: 'Show the empty text in the table'


views.style.default_summary:
  type: mapping
  label: 'Summary options'
  mapping:
    base_path:
      type: string
      label: 'Base path'
    count:
      type: boolean
      label: 'Display record count with link'
    override:
      type: boolean
      label: 'Override number of items to display'
    items_per_page:
      type: integer
      label: 'Items to display'

views.style.rss:
  type: mapping
  label: 'RSS Feed'
  mapping:
    description:
      type: label
      label: 'RSS description'

views.style.unformatted_summary:
  type: mapping
  label: 'Unformatted'
  mapping:
    inline:
      type: boolean
      label: 'Display items inline'
    separator:
      type: string
      label: 'Separator'
