# View definition (multiple)
views.view.*:
  type: mapping
  label: 'View'
  mapping:
    disabled:
      type: boolean
      label: 'Disabled'
    api_version:
      label: 'API version'
    module:
      label: 'Module'
    name:
      label: 'Machine name'
    description:
      type: text
      label: 'Administrative description'
    tag:
      label: 'Tag'
    base_table:
      label: 'Base table'
    base_field:
      label: 'Base field'
    human_name:
      type: label
      label: 'Human readable name'
    core:
      label: 'Drupal version'
    uuid:
      label: 'UUID'
    display:
      type: sequence
      label: 'Displays'
      sequence:
        - type: mapping
          label: 'Display settings'
          mapping:
            id:
              label: 'Machine name'
            display_title:
              type: text
              label: 'Title'
            display_plugin:
              label: 'Display plugin'
            position:
              type: integer
              label: 'Position'
            display_options:
              type: 'views.display.[%parent.display_plugin]'

# Views display: common
# Options for Drupal\views\Plugin\views\display\DisplayPluginBase
views.display.*:
  type: mapping
  label: 'Display options'
  mapping:
    title:
      type: text
      label: 'Display title'
    format:
      label: 'Format'
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        - type: 'views.field.[table]-[field]'
    pager:
      type: mapping
      label: 'Pager'
      mapping:
        type:
          label: 'Pager type'
        options:
          type: mapping
          label: 'Options'
          mapping:
            offset:
              type: integer
              label: 'Offset'

    exposed_form:
      type: mapping
      label: 'Exposed form'
      mapping:
        type:
          label: 'Exposed form type'
    access:
      type: mapping
      label: 'Access'
      mapping:
        type:
          label: 'Access type'
    other:
      label: 'Other'
    cache:
      type: mapping
      label: 'Cache'
      mapping:
        type:
          label: 'Cache type'
    sorts:
      type: sequence
      label: 'Sorts'
      sequence:
        - type: 'views.sort.[table]-[field]'
    arguments:
      type: sequence
      label: 'Arguments'
      sequence:
        - type: 'views.argument.[table]-[field]'
    filters:
      type: sequence
      label: 'Filters'
      sequence:
        - type: 'views.filter.[table]-[field]'
    style:
      type: mapping
      label: 'Style'
      mapping:
        type:
          label: 'Type'
    row:
      type: mapping
      label: 'Row'
      mapping:
        type:
          label: 'Row type'
        options:
          include: 'views.row.[%parent.type]'
    query:
      type: mapping
      label: 'Query'
      mapping:
        type:
          label: 'Query type'
        options:
          type: mapping
          label: 'Query options'
          mapping:
            query_comment:
              type: boolean
              label: 'Query comment'
    defaults:
      type: mapping
      label: 'Defaults'
      mapping:
        style_plugin:
          label: 'Style plugin'
        style_options:
          type: 'views.style.[%parent.style_plugin]'
        row_plugin:
          label: 'Row plugin'
        row_options:
          type: 'views.style.[%parent.row_plugin]'
    relationships:
      type: sequence
      label: 'Relationships'
      sequence:
        - type: 'views.relationship.[table]-[field]'

# Options for Drupal\views\Plugin\views\display\PathPluginBase
views.display.PathPluginBase:
  include: 'views.display.%'
  type: mapping
  mapping:
    path:
      type: string
      label: 'Page path'

# Views display plugin: Drupal\views\Plugin\views\display\Page
views.display.page:
  type: 'views.display.PathPluginBase'
  label: 'Page display options'
  mapping:
    menu:
      type: mapping
      label: 'Menu'
      mapping:
        type:
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: integer
          label: 'Weight'
        name:
          label: 'Menu name'
        context:
          label: 'Context'
    tab_options:
      type: mapping
      label: 'Tab options'
      mapping:
        type:
          label: 'Type'
        title:
          type: text
          label: 'Title'
        description:
          type: text
          label: 'Description'
        weight:
          type: integer
          label: 'Weight'
        name:
          label: 'Menu name'

# Views display plugin: Drupal\views\Plugin\views\display\Block
views.display.block:
  type: 'views.display.%'
  label: 'Block display options'
  mapping:
    block_description:
      type: text
      label: 'Block name'
    block_caching:
      label: 'Block caching'

# Views display plugin: Drupal\views\Plugin\views\display\Feed
views.display.feed:
  type: 'views.display.PathPluginBase'
  label: 'Feed display options'
  mapping:
    sitename_title:
      type: boolean
      label: 'Use the site name for the title'
    displays:
      label: 'The feed icon will be available only to the selected displays.'
