# Schema for the configuration files of the Taxonomy module.

taxonomy.settings:
  type: mapping
  label: 'Taxonomy settings'
  mapping:
    maintain_index_table:
      type: boolean
      label: 'Maintain index table'
    override_selector:
      type: boolean
      label: 'Override selector'
    terms_per_page_admin:
      type: integer
      label: 'Number of terms per page'

taxonomy.vocabulary.*:
  type: config_entity
  label: 'Vocabulary'
  mapping:
    name:
      type: label
      label: 'Name'
    vid:
      type: string
      label: 'Machine name'
    description:
      type: label
      label: 'Description'
    hierarchy:
      type: integer
      label: 'Hierarchy'
    weight:
      type: integer
      label: 'Weight'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        - type: taxonomy.vocabulary.third_party.[%key]

field.taxonomy_term_reference.storage_settings:
  type: base_entity_reference_field_settings
  label: 'Taxonomy term reference settings'
  mapping:
    options_list_callback:
      type: string
      label: 'Options list callback'
    allowed_values:
      type: sequence
      label: 'Allowed values'
      sequence:
        - type: mapping
          label: 'Allowed values'
          mapping:
            vocabulary:
              type: string
              label: 'Vocabulary'
            parent:
              type: integer
              value: 'Parent'

field.taxonomy_term_reference.field_settings:
  type: mapping
  label: 'Taxonomy term reference settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'

field.taxonomy_term_reference.value:
  type: sequence
  label: 'Default values'
  sequence:
    - type: mapping
      label: 'Default value'
      mapping:
        target_id:
          type: integer
          label: 'Term ID'

entity_view_display.field.entity_reference_rss_category:
  type: entity_field_view_display_base
  label: 'Taxonomy format settings'

entity_view_display.field.taxonomy_term_reference_plain:
  type: entity_field_view_display_base
  label: 'Taxonomy format settings'

entity_view_display.field.taxonomy_term_reference_rss_category:
  type: entity_field_view_display_base
  label: 'Taxonomy format settings'

entity_view_display.field.taxonomy_term_reference_link:
  type: entity_field_view_display_base
  label: 'Taxonomy format settings'

entity_form_display.field.taxonomy_autocomplete:
  type: entity_field_form_display_base
  label: 'Autocomplete term widget (tagging) format settings'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        size:
          type: integer
          label: 'Size'
        autocomplete_route_name:
          type: string
          label: 'Autocomplete route name'
        placeholder:
          type: label
          label: 'Placeholder'
