# The menu migration is in the system module and the menu_links migration is in the menu_link_content module.
id: menu_settings
label: Menu UI configuration
migration_tags:
  - Drupal 6
  - Drupal 7
source:
  plugin: variable
  variables:
    - menu_override_parent_selector
  source_module: menu
process:
  override_parent_selector: menu_override_parent_selector
destination:
  plugin: config
  config_name: menu_ui.settings
