# Schema for the views plugins of the Aggregator module.

views.argument.aggregator_fid:
  type: views.argument.numeric
  label: 'Aggregator feed ID'

views.argument.aggregator_iid:
  type: views.argument.numeric
  label: 'Aggregator item ID'

views.field.aggregator_title_link:
  type: views_field
  label: 'Title link'
  mapping:
    display_as_link:
      type: boolean
      label: 'Display as link'

views.field.aggregator_xss:
  type: views.field.xss
  label: 'Aggregator XSS'

views.row.aggregator_rss:
  type: views_row
  label: 'Aggregator item row'
  mapping:
    item_length:
      type: string
      label: 'Display type'
