entity.block.settings_tray_form:
  path: '/admin/structure/block/manage/{block}/settings-tray'
  defaults:
    _entity_form: 'block.settings_tray'
    _title_callback: '\Drupal\settings_tray\Block\BlockEntitySettingTrayForm::title'
  requirements:
    _permission: 'administer blocks'
    _access_block_plugin_has_settings_tray_form: 'TRUE'
    _access_block_has_overrides_settings_tray_form: 'TRUE'
