id: d6_language_negotiation_settings
label: Language negotiation settings
migration_tags:
  - Drupal 6
  - Configuration
source:
  plugin: variable
  variables:
    - language_negotiation
  source_module: locale
process:
  session/parameter:
    plugin: default_value
    default_value: 'language'
  selected_langcode:
    plugin: default_value
    default_value: 'site_default'
  url/source:
    plugin: static_map
    source: language_negotiation
    default_value: path_prefix
    map:
      # LANGUAGE_NEGOTIATION_NONE = 0
      # LANGUAGE_NEGOTIATION_PATH_DEFAULT = 1
      # LANGUAGE_NEGOTIATION_PATH = 2
      # LANGUAGE_NEGOTIATION_DOMAIN = 3
      0: path_prefix
      1: path_prefix
      2: path_prefix
      3: domain
destination:
  plugin: config
  config_name: language.negotiation
migration_dependencies:
  required:
    - language
